// <auto-generated />
using System;
using CaiAdmin.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaiAdmin.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CaiAdmin.Entity.Attach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeleteUserId")
                        .HasColumnType("int");

                    b.Property<Guid>("EntityGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Attach");
                });

            modelBuilder.Entity("CaiAdmin.Entity.Sys.Api", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCommon")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasFilter("[Path] IS NOT NULL");

                    b.ToTable("SysApi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCommon = false,
                            Name = "获取接口分页列表",
                            Path = "/Sys/Api/GetPageList",
                            PermissionType = 0
                        },
                        new
                        {
                            Id = 2,
                            IsCommon = false,
                            Name = "删除接口",
                            Path = "/Sys/Api/DeleteById",
                            PermissionType = 1
                        },
                        new
                        {
                            Id = 3,
                            IsCommon = false,
                            Name = "保存接口",
                            Path = "/Sys/Api/Save",
                            PermissionType = 1
                        },
                        new
                        {
                            Id = 4,
                            IsCommon = true,
                            Name = "获取接口公共分页列表",
                            Path = "/Sys/Api/GetCommonPageList",
                            PermissionType = 0
                        },
                        new
                        {
                            Id = 5,
                            IsCommon = true,
                            Name = "获取角色公共选项列表",
                            Path = "/Sys/Role/GetCommonOptionList",
                            PermissionType = 0
                        },
                        new
                        {
                            Id = 6,
                            IsCommon = false,
                            Name = "获取角色分页列表",
                            Path = "/Sys/Role/GetPageList",
                            PermissionType = 0
                        });
                });

            modelBuilder.Entity("CaiAdmin.Entity.Sys.Config", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("SysConfig");

                    b.HasData(
                        new
                        {
                            Key = "SYSTEM_TITLE",
                            Name = "系统标题",
                            Type = "STRING",
                            Value = "LessAdmin快速开发框架"
                        },
                        new
                        {
                            Key = "MENU_BAR_TITLE",
                            Name = "菜单栏标题",
                            Type = "STRING",
                            Value = "LessAdmin"
                        },
                        new
                        {
                            Key = "VERSION",
                            Name = "版本号",
                            Type = "STRING",
                            Value = "20200414001"
                        },
                        new
                        {
                            Key = "IS_REPAIR",
                            Name = "网站维护",
                            Type = "BOOL",
                            Value = "OFF"
                        },
                        new
                        {
                            Key = "LAYOUT",
                            Name = "后台布局",
                            Type = "STRING",
                            Value = "leftRight"
                        },
                        new
                        {
                            Key = "LIST_DEFAULT_PAGE_SIZE",
                            Name = "列表默认页容量",
                            Type = "NUMBER",
                            Value = "10"
                        },
                        new
                        {
                            Key = "MENU_DEFAULT_ICON",
                            Name = "菜单默认图标",
                            Type = "STRING",
                            Value = "el-icon-menu"
                        },
                        new
                        {
                            Key = "SHOW_MENU_ICON",
                            Name = "是否显示菜单图标",
                            Type = "BOOL",
                            Value = "OFF"
                        },
                        new
                        {
                            Key = "LOGIN_VCODE",
                            Name = "登录需要验证码",
                            Type = "BOOL",
                            Value = "OFF"
                        },
                        new
                        {
                            Key = "PAGE_TABS",
                            Name = "使用多页面标签",
                            Type = "BOOL",
                            Value = "ON"
                        });
                });

            modelBuilder.Entity("CaiAdmin.Entity.Sys.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CanMultipleOpen")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRead")
                        .HasColumnType("bit");

                    b.Property<bool>("HasReview")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWrite")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPage")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("ParentIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SysMenu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanMultipleOpen = false,
                            HasRead = false,
                            HasReview = false,
                            HasWrite = false,
                            IsPage = false,
                            Name = "系统管理",
                            Order = 99,
                            Path = "sys"
                        },
                        new
                        {
                            Id = 2,
                            CanMultipleOpen = false,
                            HasRead = true,
                            HasReview = false,
                            HasWrite = true,
                            IsPage = false,
                            Name = "用户管理",
                            Order = 1,
                            ParentId = 1,
                            ParentIds = "1",
                            Path = "user"
                        },
                        new
                        {
                            Id = 3,
                            CanMultipleOpen = false,
                            HasRead = true,
                            HasReview = false,
                            HasWrite = true,
                            IsPage = false,
                            Name = "角色管理",
                            Order = 2,
                            ParentId = 1,
                            ParentIds = "1",
                            Path = "role"
                        },
                        new
                        {
                            Id = 4,
                            CanMultipleOpen = false,
                            HasRead = true,
                            HasReview = false,
                            HasWrite = true,
                            IsPage = false,
                            Name = "菜单管理",
                            Order = 3,
                            ParentId = 1,
                            ParentIds = "1",
                            Path = "menu"
                        },
                        new
                        {
                            Id = 5,
                            CanMultipleOpen = false,
                            HasRead = true,
                            HasReview = false,
                            HasWrite = true,
                            IsPage = false,
                            Name = "接口管理",
                            Order = 4,
                            ParentId = 1,
                            ParentIds = "1",
                            Path = "api"
                        },
                        new
                        {
                            Id = 6,
                            CanMultipleOpen = false,
                            HasRead = true,
                            HasReview = false,
                            HasWrite = true,
                            IsPage = false,
                            Name = "配置管理",
                            Order = 5,
                            ParentId = 1,
                            ParentIds = "1",
                            Path = "config"
                        },
                        new
                        {
                            Id = 7,
                            CanMultipleOpen = false,
                            HasRead = true,
                            HasReview = false,
                            HasWrite = true,
                            IsPage = false,
                            Name = "Token管理",
                            Order = 6,
                            ParentId = 1,
                            ParentIds = "1",
                            Path = "token"
                        });
                });

            modelBuilder.Entity("CaiAdmin.Entity.Sys.MenuApi", b =>
                {
                    b.Property<int>("ApiId")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.HasKey("ApiId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("SysMenuApi");
                });

            modelBuilder.Entity("CaiAdmin.Entity.Sys.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("SysRole");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "超级角色",
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CaiAdmin.Entity.Sys.RoleMenu", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<bool>("CanRead")
                        .HasColumnType("bit");

                    b.Property<bool>("CanReview")
                        .HasColumnType("bit");

                    b.Property<bool>("CanWrite")
                        .HasColumnType("bit");

                    b.HasKey("RoleId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("SysRoleMenu");
                });

            modelBuilder.Entity("CaiAdmin.Entity.Sys.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AccessExpire")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RefreshExpire")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SysToken");
                });

            modelBuilder.Entity("CaiAdmin.Entity.Sys.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoginName")
                        .IsUnique()
                        .HasFilter("[LoginName] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("SysUser");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDisabled = false,
                            LoginName = "superadmin",
                            LoginPassword = "admin",
                            RoleId = -1,
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CaiAdmin.Entity.Sys.UserLoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SysUserLoginLog");
                });

            modelBuilder.Entity("CaiAdmin.Entity.Sys.MenuApi", b =>
                {
                    b.HasOne("CaiAdmin.Entity.Sys.Api", "Api")
                        .WithMany("MenuApis")
                        .HasForeignKey("ApiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CaiAdmin.Entity.Sys.Menu", "Menu")
                        .WithMany("MenuApis")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CaiAdmin.Entity.Sys.RoleMenu", b =>
                {
                    b.HasOne("CaiAdmin.Entity.Sys.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CaiAdmin.Entity.Sys.Role", "Role")
                        .WithMany("RoleMenus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CaiAdmin.Entity.Sys.Token", b =>
                {
                    b.HasOne("CaiAdmin.Entity.Sys.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CaiAdmin.Entity.Sys.User", b =>
                {
                    b.HasOne("CaiAdmin.Entity.Sys.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CaiAdmin.Entity.Sys.UserLoginLog", b =>
                {
                    b.HasOne("CaiAdmin.Entity.Sys.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
